# Generated by Django 5.2.4 on 2025-08-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajes',
            old_name='usuario',
            new_name='user',
        ),
    ]
