# Generated by Django 5.2.4 on 2025-08-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCliente', '0002_rename_usuario_mensajes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='user',
        ),
        migrations.AddField(
            model_name='mensajes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mensajes',
            name='nombre',
            field=models.CharField(default='hola@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
