# Generated by Django 5.2.4 on 2025-08-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCliente', '0003_remove_mensajes_user_mensajes_email_mensajes_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_user',
            field=models.CharField(default='cliente', max_length=20),
            preserve_default=False,
        ),
    ]
